"""add columns to player

Revision ID: f23ee82439d5
Revises: 
Create Date: 2026-02-06 09:08:32.051566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23ee82439d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('squad_no', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('squad_no')
        batch_op.drop_column('goals')

    # ### end Alembic commands ###
